spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mysuperlongsecretkey1234567890abcd1234abcd5678
  expiration: 86400000 # 1 day
